pyside6-uic main.ui -o ui_main.py
pyside6-uic ParamNet.ui -o ui_ParamNet.py
pyside6-uic CreatePass.ui -o ui_CreatePass.py
pyside6-uic Error.ui -o ui_Error.py
pyside6-uic Success.ui -o ui_Success.py
pyside6-uic StandardName.ui -o ui_StandardName.py
pyside6-uic YesNo.ui -o ui_YesNo.py
pyside6-uic EditNetwork.ui -o ui_EditNetwork.py
pyside6-uic DisableUser.ui -o ui_DisableUser.py
pyside6-uic DomainName.ui -o ui_DomainName.py
pyside6-uic DomainName.ui -o ui_DomainName.py
pyside6-uic DataServer.ui -o ui_DataServer.py
pyside6-uic Programs.ui -o ui_Programs.py